In [1]:
import numpy as np

# power of numpy vs python lists 

In [2]:
%%time
list1 = [i for i in range(100000)]

CPU times: total: 0 ns
Wall time: 4.42 ms


In [3]:
%%time 
arr = np.arange(100000)

CPU times: total: 0 ns
Wall time: 565 μs


In [4]:
%%time
new_list = [x * 5 for x in list1]

CPU times: total: 15.6 ms
Wall time: 6.54 ms


In [5]:
%%time
new_arr = arr * 5 

CPU times: total: 0 ns
Wall time: 909 μs


In [6]:
new_arr

array([     0,      5,     10, ..., 499985, 499990, 499995])

# Array creation Data Types 

In [7]:
arr_1d = np.arange(1 , 10)

In [8]:
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [10]:
arr_2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr_1d.ndim

1

In [12]:
arr_2d.ndim

2

In [13]:
arr_1d.shape


(9,)

In [14]:
arr_1d.size

9

In [15]:
arr_2d.shape


(3, 3)

In [16]:
arr_2d.size


9

In [17]:
print("arr_2d  dtype:", arr_2d.dtype, ",  itemsize:", arr_2d.itemsize, "bytes")

arr_2d  dtype: int64 ,  itemsize: 8 bytes


In [18]:
array = np.array ([[1.22,2.01,3.02],[4.04,5.07,6.02],[7.55,8.67,9.07]])

In [19]:
array

array([[1.22, 2.01, 3.02],
       [4.04, 5.07, 6.02],
       [7.55, 8.67, 9.07]])

In [20]:
array.astype(int)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Creation Function 


In [21]:
zeros = np.zeros([4,4])

In [22]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
one_matrix = np.ones([3,2])

In [24]:
one_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
ide_matrix = np.identity(5)

In [26]:
ide_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
matrix = np.full((3,3),7)

In [28]:
matrix

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [29]:
random_arr = np.empty((3,4))

In [30]:
random_arr

array([[1.34780034e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 2.62661521e+179, 2.89882003e-057,
        9.06328246e-043],
       [4.08658382e+179, 1.25581324e-071, 1.85554194e-051,
        2.27285050e+184]])

In [31]:
random_int = np.random.randint(10,99, size = (3,4))

In [32]:
random_int

array([[29, 79, 62, 76],
       [37, 39, 95, 56],
       [88, 58, 50, 87]], dtype=int32)

In [33]:
arr_arang = np.arange(5 , 50 , 5)

In [34]:
arr_arang

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [35]:
arr_arang.reshape(3,3)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# Indexing and Slicing 

In [36]:
arr_arr = np.array([[10,20,30,40],[50,60,70,80],[90,100.,110,120]])
arr_arr

array([[ 10.,  20.,  30.,  40.],
       [ 50.,  60.,  70.,  80.],
       [ 90., 100., 110., 120.]])

In [37]:
arr_extract = arr_arr[1]
arr_extract

array([50., 60., 70., 80.])

In [38]:
arr_extract = arr_arr[:2, 2:]
arr_extract

array([[30., 40.],
       [70., 80.]])

In [39]:
arr_extract = arr_arr[2:]
arr_extract

array([[ 90., 100., 110., 120.]])

In [40]:
arr_arr[1] = [1,2,3,4]
arr_arr

array([[ 10.,  20.,  30.,  40.],
       [  1.,   2.,   3.,   4.],
       [ 90., 100., 110., 120.]])

# vectorization


In [41]:
A = np.random.randint(1,10,5)
B = np.random.randint(1,10,5)
A


array([6, 1, 7, 7, 6], dtype=int32)

In [42]:
B

array([4, 2, 6, 1, 6], dtype=int32)

In [43]:
Addition = A + B
Addition

array([10,  3, 13,  8, 12], dtype=int32)

In [44]:
Subtraction = A - B
Subtraction

array([ 2, -1,  1,  6,  0], dtype=int32)

In [45]:
Multiplication = A * B
Multiplication

array([24,  2, 42,  7, 36], dtype=int32)

In [46]:
Division = A / B
Division

array([1.5       , 0.5       , 1.16666667, 7.        , 1.        ])

In [47]:
arr_1 = np.array([1,2,3,4,55])
arr_1

array([ 1,  2,  3,  4, 55])

In [48]:
sqrt = np.sqrt(arr_1)
sqrt

array([1.        , 1.41421356, 1.73205081, 2.        , 7.41619849])

In [49]:
exp = np.exp(arr_1)
exp

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       7.69478527e+23])

In [50]:
sin = np.sin(arr_1)
sin

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.99975517])

In [51]:
celsius = np.array([1,2,3,0,5,6,7,5,8,10])
fahrenheit = (celsius * 9/5) + 32
fahrenheit


array([33.8, 35.6, 37.4, 32. , 41. , 42.8, 44.6, 41. , 46.4, 50. ])

# Broadcasting 

In [52]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
add = A + 10
add

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [54]:
row_vector = np.array([[1,2,3]])
row_vector

array([[1, 2, 3]])

In [55]:
result = A + row_vector
result

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [56]:
vector_2 = [[1],[2],[3]]


In [57]:
result_2 = A + vector_2 
result_2

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [58]:
shape = np.shape(result_2)
shape

(3, 3)

# Reshape , Flatten , Ravel

In [68]:
reshape = np.arange(1 , 13) 
reshape

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
rshape = reshape.reshape(3, 4)
rshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
rshape_1 = reshape.reshape(2, 6)
rshape_1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [71]:
flt = reshape.flatten()
flt

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
ravel = reshape.ravel()
ravel

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
arr_9 = np.arange(1,10).reshape(3,3)
arr_9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
flt_1 = arr_9.flatten()
flt_1

array([  1, 200,   3,   4,   5,   6,   7,   8,   9])

In [76]:
ravel_1 = arr_9.ravel()
ravel_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
flt_1[0] = 100
ravel_1[1] = 200




In [87]:
flt_1

array([100, 200,   3,   4,   5,   6,   7,   8,   9])

In [86]:
ravel_1

array([  1, 200,   3,   4,   5,   6,   7,   8,   9])